[package]
name = "arc-mutex-di"
version = "0.1.0"
edition = "2021"

[dependencies]
shared-dependencies = { path = "../shared-dependencies" }
tokio = { version = "1.32", features = ["full"] }
async-trait = "0.1.68"
uuid = { version = "1.4", features = ["v4"] }